### ISSUE TITLE
Bug: I have seen an error or well I think so, when using .breload item ID by console the server crashes

### ISSUE THREAD

**Issue by jedagutavito** [azerothcore/mod-betteritemreloading#10]
### Current Behaviour

.breload item ID in console

### Expected Behaviour

It should reload with no problem.

### Steps to reproduce the problem

Just use the .breload item ID command

### AC rev. hash/commit

Does not have

### Operating system

Ubuntu

**Comment by pangolp** [comment]
Please, do not forget to put the hash of the AzerothCore compilation that you are using, because a compilation from yesterday is not the same as one from 2 years ago. To see that, you can do a .server info and check what is the hash that shows you. If you downloaded the .zip, you probably don't have a hash, but that's important to know.

**Comment by jedagutavito** [comment]
Last version

**Comment by pangolp** [comment]
> Last version

Paste the URL where it says the hash in that case. So it remains with today's date. If you're really using the latter. And if you are using one from last week, put the one from last week. In case of being the last one, you put this: https://github.com/azerothcore/azerothcore-wotlk/commit/5085dea25e9ab248615f4dcecbe410e3d2df91a1
